### ISSUE TITLE
com.parse.ParseRequest$ParseRequestException: bad json response

### ISSUE THREAD

**Issue by lawonga** [ParsePlatform/Parse-SDK-Android#334]
This is not just bad json response, it is more like I cannot initialize parse (it was working earlier) with minimally changed code. I have code that when I compile on my laptop or my desktop it fails to activate cloud code. Reverting to an older version and re-compiling does not work. However, installing the apk I had generated for that version DID work. So I have narrowed it down to some sort of compiling/maven library issue.

What I need to know is if my assumptions are correct - and if it is a server side/maven/parse library issue.

These appear to be related:
ANDROID:
https://groups.google.com/forum/#!topic/parse-developers/jdCEIBh5RaE
https://groups.google.com/forum/#!topic/parse-developers/5r7ghKL3V80
https://groups.google.com/forum/#!topic/parse-developers/lqCNcHKTKeM
https://groups.google.com/forum/#!topic/parse-developers/c6skB4RlfEE
IOS:
https://groups.google.com/forum/#!topic/parse-developers/QqCrgTYA9Q8

My posting on stackoverflow:
http://stackoverflow.com/questions/34627501/parse-function-suddenly-returning-invalid-json?noredirect=1#comment57000364_34627501

**Comment by andriusic** [comment]
I was facing the same issue, seems like a bug from recent builds, rolled back to 1.10.0 and it's working. It's a workaround while its fixed

**Comment by lawonga** [comment]
Excellent. Now I know I'm not crazy. Thanks!

**Comment by wangmengyan95** [comment]
Hi @lawonga
1. In your stackoverflow thread, I see `<html>` from your response json. Our server does not return this kind of response. I wonder do you use some proxy on top of you android network stack?
2. Could you try our [REST API](https://www.parse.com/docs/rest/guide#cloud-code) to see whether you can repo this issue?

**Comment by lawonga** [comment]
Hello @wangmengyan95 

1. I did a bit more digging yesterday and I found out that I simply could not initialize parse. In fact, parse wasn't actually functional on the app. The `<html>` sure does seem strange though. Maybe the debugger recognizes or defaults to json?

2. I'll take a look when I get home later, but I have fixed the error by changing my:
`compile 'com.parse:parse-android:1.+'`
to
`compile 'com.parse:parse-android:1.12.0'

**Comment by grantland** [comment]
@lawonga would you be happening to be using the SNAPSHOT builds? If you're unsure, could you post the contents of your `build.gradle` files?

**Comment by lawonga** [comment]
App build gradle: 

`apply plugin: 'com.android.application'

android {
    compileSdkVersion 23
    buildToolsVersion "23.0.1"

    defaultConfig {
        applicationId "recruitr.recruitr"
        minSdkVersion 19
        targetSdkVersion 23
        versionCode 1
        versionName "1.0"
    }
    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android.txt'), 'proguard-rules.pro'
        }
    }
}
repositories {
    mavenCentral()
    maven {
        url "https://oss.sonatype.org/content/repositories/snapshots"
    }
    maven { url "https://jitpack.io" }
}
dependencies {
    compile fileTree(dir: 'libs', include: ['*.jar'])
    testCompile 'junit:junit:4.12'
    compile 'com.android.support:appcompat-v7:23.1.0'
    compile 'com.android.support:design:23.1.0'
    compile 'com.parse.bolts:bolts-android:1.+'
    compile 'com.parse:parse-android:1.12.0'
    compile 'com.facebook.android:facebook-android-sdk:4.6.0'
    compile 'com.parse:parsefacebookutils-v4-android:1.10.3@aar'
    compile 'de.hdodenhof:circleimageview:2.0.0'
    compile 'com.akexorcist:RoundCornerProgressBar:2.0.3'
}`

**Comment by grantland** [comment]
Ah yeah you are using snapshots for some reason:

```
maven {
    url "https://oss.sonatype.org/content/repositories/snapshots"
}
```

This means that you are using the latest build in master of this repository rather than an explicit build that we've released. I'd recommend to either remove those lines to disable the use of snapshots or to include explicit version numbers on your dependencies.

**Comment by lawonga** [comment]
Awesome, thanks!

**Comment by vineetbindal** [comment]
@grantland Hi,

I have been getting the same error : 

Here are dependencies I am using. 
dependencies {
    compile 'com.android.support:support-v4:23.0.0'
    compile 'com.android.support:appcompat-v7:23.0.0'
    compile 'com.parse.bolts:bolts-android:1.+'
    compile 'com.parse:parse-android:1.13.0'
    compile files('libs/simmetrics_jar_v1_6_2_d07_02_07.jar')
    compile('com.digits.sdk.android:digits:1.9.3@aar') {
        transitive = true;
    }
}

**Comment by ixorakos** [comment]
Using compile 'com.parse:parse-android:1.13.0' and issue still persists.

**Comment by vineetbindal** [comment]
@ixorakos check [HERE](https://github.com/ParsePlatform/parse-server/issues/795#issuecomment-192106136)

Solution is : fix  it by adding "/" to the end of server. 
"http://10.0.2.2:1337/parse" -> "http://10.0.2.2:1337/parse/"

**Comment by shukerullah** [comment]
@vineetbindal thanks

**Comment by aberguesb** [comment]
awesome fix vineetbindal

**Comment by nomanr** [comment]
Tried old versions and "/", still get the same response. 
`org.json.JSONException: Value <html> of type java.lang.String cannot be converted to JSONObject`

**Comment by sarthak1492** [comment]
I am getting the same error. I was using ```compile 'com.parse:parse-android:1.13.0'```, but I changed it to ```compile 'com.parse:parse-android:1.12.0'```.

But while using this code:
```
Parse.initialize(new Parse.Configuration.Builder(getApplicationContext())
            .applicationId("MY_APP_ID")
            .clientKey("MY_CLIENT_ID")
            .server("https://abc-xyz.herokuapp.com/parse/").build()

);
```

// it gives ```'cannot resolve symbol'``` on ```server(url).build()```.
